services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: smart_logistic
      POSTGRES_USER: smart_logistic
      POSTGRES_PASSWORD: smart_logistic
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"

volumes:
  postgres-data:
