-- Provincias oficiales de Chile (56), codigo = codigo provincia INE
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (11, 'Iquique', 1);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (14, 'Tamarugal', 1);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (21, 'Antofagasta', 2);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (22, 'El Loa', 2);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (23, 'Tocopilla', 2);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (31, 'Copiapó', 3);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (32, 'Chañaral', 3);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (33, 'Huasco', 3);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (41, 'Elqui', 4);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (42, 'Choapa', 4);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (43, 'Limarí', 4);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (51, 'Valparaíso', 5);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (52, 'Isla de Pascua', 5);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (53, 'Los Andes', 5);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (54, 'Petorca', 5);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (55, 'Quillota', 5);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (56, 'San Antonio', 5);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (57, 'San Felipe de Aconcagua', 5);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (58, 'Marga Marga', 5);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (61, 'Cachapoal', 6);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (62, 'Cardenal Caro', 6);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (63, 'Colchagua', 6);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (71, 'Talca', 7);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (72, 'Cauquenes', 7);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (73, 'Curicó', 7);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (74, 'Linares', 7);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (81, 'Concepción', 8);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (82, 'Arauco', 8);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (83, 'Biobío', 8);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (91, 'Cautín', 9);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (92, 'Malleco', 9);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (101, 'Llanquihue', 10);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (102, 'Chiloé', 10);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (103, 'Osorno', 10);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (104, 'Palena', 10);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (111, 'Coihaique', 11);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (112, 'Aisén', 11);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (113, 'Capitán Prat', 11);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (114, 'General Carrera', 11);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (121, 'Magallanes', 12);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (122, 'Antártica Chilena', 12);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (123, 'Tierra del Fuego', 12);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (124, 'Última Esperanza', 12);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (131, 'Santiago', 13);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (132, 'Cordillera', 13);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (133, 'Chacabuco', 13);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (134, 'Maipo', 13);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (135, 'Melipilla', 13);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (136, 'Talagante', 13);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (141, 'Valdivia', 14);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (142, 'Ranco', 14);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (151, 'Arica', 15);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (152, 'Parinacota', 15);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (161, 'Punilla', 16);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (162, 'Itata', 16);
INSERT INTO provincia (codigo, nombre, region_codigo) VALUES (163, 'Diguillín', 16);
